### ISSUE TITLE
TyporaCrack 被 DMCA Takedown了

### ISSUE THREAD

**Issue by TakumiBC** [SnapdragonLee/SnapdragonLee#1]
刚刚发现大佬的 TyporaCrack 被 DMCA Takedown了。现阶段是建议用其他项目，还是说会在GitLab 等平台继续发布？
：）

**Comment by SnapdragonLee** [comment]
hhh 说一下啊，我不是大佬

然后 可以加入电报频道：https://t.me/tybetter
电报群：https://t.me/cracyty
这个里面有你要的信息

**Comment by SnapdragonLee** [comment]
最新的公告：


The latest TyporaCrack link is: https://github.com/Delppine1024/TyporaGreen

It will set public at 2022.4.18 22:00 - 23:00 (UTC+8:00)


Subscribe this channel, and you will get what you want.

**Comment by SnapdragonLee** [comment]
还有 本人不会再提供任何的维护业务，其他的信息请在群里看吧
